version: "3.9"

services:
  web:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - ./entrypoint.sh:/app/entrypoint.sh:ro
      - app_data:/data
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - PYTHONUNBUFFERED=1 
    networks:
      - webnet
    tty: true
    command: ["/bin/bash", "./entrypoint.sh"]

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=testdb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - webnet
networks:
  webnet:

volumes:
  app_data:
  db_data: